export enum StatusCode {
  INCORRECT_LOGIN = 'INCORRECT_LOGIN',
  UNAUTHORIZED = 'UNAUTHORIZED',
  USER_ALREADY_ACTIVATED = 'USER_ALREADY_ACTIVATED',
  ACTIVATION_CODE_NOT_FOUND = 'ACTIVATION_CODE_NOT_FOUND',
  NOT_EMPTY = 'NOT_EMPTY',
  IS_EMAIL = 'IS_EMAIL',
  STRING_LENGTH = 'STRING_LENGTH',
  NUMBER_LENGTH = 'NUMBER_LENGTH',
  EMAIL_USED = 'EMAIL_USED',
  IS_DATE = 'IS_DATE',
  MAX_DATE = 'MAX_DATE'
}